"""add campo token na tabela usuario

Revision ID: 459b3d4929ee
Revises: 88a6a5e01220
Create Date: 2023-12-12 09:17:10.571055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459b3d4929ee'
down_revision: Union[str, None] = '88a6a5e01220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token')
    # ### end Alembic commands ###
