"""add campo diretorio_img na tabela produto e campo email nas tabelas fornecedor e usuario

Revision ID: 88a6a5e01220
Revises: dbe55830acfd
Create Date: 2023-12-10 12:17:50.125227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a6a5e01220'
down_revision: Union[str, None] = 'dbe55830acfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedors', sa.Column('email', sa.String(), nullable=False))
    op.add_column('produtos', sa.Column('diretorio_img', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'email')
    op.drop_column('produtos', 'diretorio_img')
    op.drop_column('fornecedors', 'email')
    # ### end Alembic commands ###
