"""Create table categoria permissao produto usuario

Revision ID: dbe55830acfd
Revises: e9ba22b27977
Create Date: 2023-12-06 09:00:20.953902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe55830acfd'
down_revision: Union[str, None] = 'e9ba22b27977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisao_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('diretorio_img', sa.String(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.String(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permisao_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fornecedores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('cnpj', sa.INTEGER(), nullable=False),
    sa.Column('telefone', sa.INTEGER(), nullable=False),
    sa.Column('endereco_id', sa.INTEGER(), nullable=False),
    sa.Column('diretorio_img', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produtos')
    op.drop_table('usuarios')
    op.drop_table('fornecedors')
    op.drop_table('permisao_usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
