"""modificando o campo email da tabela usuarios, deixando ele unico

Revision ID: ed6f2070594f
Revises: 459b3d4929ee
Create Date: 2023-12-12 10:50:09.950871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6f2070594f'
down_revision: Union[str, None] = '459b3d4929ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_usuarios_email', ['email'])

        """
        O "batch mode" do Alembic permite que as alterações sejam feitas em uma cópia da tabela original. A tabela original é então removida e a cópia é renomeada para substituí-la. Isso permite realizar operações que normalmente não são suportadas pelo SQLite, como adicionar uma restrição de chave única.
        """


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    # ### end Alembic commands ###
