"""Adicionando Coluna para diretorio de imagens para fornecedor

Revision ID: ef4ce7a7a31c
Revises: dbdad3b53c57
Create Date: 2023-12-05 22:09:35.468418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4ce7a7a31c'
down_revision: Union[str, None] = 'dbdad3b53c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedores', sa.Column('diretorio_img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fornecedores', 'diretorio_img')
    # ### end Alembic commands ###
